### ISSUE TITLE
Provide a way to link from the visualizer to resource logs

### ISSUE THREAD

**Issue by sbueringer** [Jont828/cluster-api-visualizer#11]
With the CAPI tilt-based dev environment it is possible to deploy CAPI providers, the visualizer and a logging stack (promtail, loki, grafana).

Here is some more information about how to deploy the logging stack: https://cluster-api.sigs.k8s.io/developer/logging.html?highlight=loki#developing-and-testing-logs

Based on our recent work on logging, all controllers (at least in core CAPI) should now include key value pairs for the currently reconciled object and related objects.

This makes it possible to filter e.g. all logs for a specific KubeadmControlPlane across controllers.

![image](https://user-images.githubusercontent.com/4662360/188167738-f79390c6-e89b-420d-b2bf-692c52328c17.png)

I think it would be great if we could pass a URL template as command line flag into the visualizer and the visualizer then adds a "logs" button on every resource.

The URL for the query above looks like this:
> http://localhost:3001/explore?orgId=1&left=%7B%22datasource%22:%22Loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bapp%3D~%5C%22.%2B%5C%22%7D%20%7C%20json%20%7C%20KubeadmControlPlane_name%3D%5C%22development-3961-4flkb%5C%22%22%7D%5D,%22range%22:%7B%22from%22:%22now-1h%22,%22to%22:%22now%22%7D%7D

I think in general it would be great if there is a way to render this URL based on:
* resource kind, name and namespace (one option could be go templating)

Please note that the k/v pairs will be further improved soon by this PR https://github.com/kubernetes-sigs/cluster-api/pull/7152 and the upcoming bump to controller-runtime v0.13.0.

**Comment by sbueringer** [comment]
cc @Jont828 @fabriziopandini

**Comment by fabriziopandini** [comment]
There is a lot of implicit assumptions for the link to work, like e.g. the user running monitoring on localhost:3001, without authentication (which is something we do on our dev env, but it isn't really recommended).
I would say let's wait/low priority + have this behind a feature flag we can turn on in our dev setup.

**Comment by sbueringer** [comment]
I think by providing the URL as a flag we don't assume that it's hostet on a specific URL.

If authentication in Grafana is enabled folks have to login, but after the login it should work.

Of course it's just low prio / nice to have :)

**Comment by Jont828** [comment]
Thanks for elaborating, at first I was imagining that we wanted to create a logs view within the app. I'm imagining we could do something like an experimental CLI flag in main.go like `--logs-url` or something. So to clarify, is Loki part of Grafana or is it something else? And is there documentation on how to construct the query (so you don't need to fill in all the % symbols)?

**Comment by sbueringer** [comment]
> at first I was imagining that we wanted to create a logs view within the app
That's probably possible as well. Loki also has a cli and I guess also a SDK. But it's probably better to defer to Grafana as the UI is more powerful.

> So to clarify, is Loki part of Grafana or is it something else? 

promtail sends the logs to Loki, Loki stores the logs, Grafana queries Loki for logs to show them in the UI
SImilar to: Prometheus pulls metrics, Grafana queries Promotheus to show metrics in the UI

> And is there documentation on how to construct the query (so you don't need to fill in all the % symbols)?
Not sure. Most of it is probably just URL encoding of strange characters like `{`

**Comment by Jont828** [comment]
Sounds good. So to clarify, in order to support this log view, would we need to enable promtail, Loki, and Grafana together in the visualizer?

**Comment by sbueringer** [comment]
You have to enable promtail, loki and grafana and the visualizer in the tilt-settings yes. Although it could work with any arbitrary log system where you can filter via URL by templating kind & resource name into the URL.

**Comment by Jont828** [comment]
Done with #47!
