### ISSUE TITLE
When cluster-api-visualizer is started it triggers an upgrade of the cluster-api control plane

### ISSUE THREAD

**Issue by primeroz** [Jont828/cluster-api-visualizer#13]
I could not figure out how this happens since i can't see any direct call to the `Upgrade` Functions of cluster-api nor any implicit one.

But while working on the `cluster-api-provider-azure` i noticed this happenening 

* start `Tilt` with `make tilt-up` from tag 1.6.0 https://github.com/kubernetes-sigs/cluster-api-provider-azure/tree/v1.6.0 of cluster-api-provider-azure
  * to isolate the problem comment every section in the observability stack other than cluster-api-visualizer
  * this will start with version 1.2.4 of the cluster-api-provider 
  * when the visualizer start the version of the cluster-api is upgraded to , current, latest 1.2.5 and the `Featureflags` are all reverted to false (which is the problem i am facing ) 

I don't think something like this is expected , i can also see that the registry changes 

**pre capi-visualizer** 
```
$ kubectl get -n capi-system deployment capi-controller-manager -o json | jq '.spec.template.spec.containers[0] | .image,.args'

"k8s.gcr.io/cluster-api/cluster-api-controller:v1.2.4"                                                   
[                                      
  "--leader-elect",                                                                                      
  "--metrics-bind-addr=localhost:8080",
  "--feature-gates=MachinePool=true,ClusterResourceSet=true,ClusterTopology=false,RuntimeSDK=false"      
]
```

**post capi-visualizer**
```
"registry.k8s.io/cluster-api/cluster-api-controller:v1.2.5"
[
  "--leader-elect",
  "--metrics-bind-addr=localhost:8080",
  "--feature-gates=MachinePool=false,ClusterResourceSet=false,ClusterTopology=false,RuntimeSDK=false"
]
```

Started `capi-visualizer` with `-v=10` i can actually see the patch request 

```
I1118 11:02:05.173549       1 request.go:1073] Request Body: {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"creationTimestamp":null,"labels":{"cluster.x-k8s.io/provider":"cluster-api","clusterctl.cluster.x-k8s.io":"","control-plane":"controller-manager"},"name":"capi-controller-manager","namespace":"capi-system","resourceVersion":"985"},"spec":{"replicas":1,"selector":{"matchLabels":{"cluster.x-k8s.io/provider":"cluster-api","control-plane":"controller-manager"}},"strategy":{},"template":{"metadata":{"creationTimestamp":null,"labels":{"cluster.x-k8s.io/provider":"cluster-api","control-plane":"controller-manager"}},"spec":{"containers":[{"args":["--leader-elect","--metrics-bind-addr=localhost:8080","--feature-gates=MachinePool=false,ClusterResourceSet=false,ClusterTopology=false,RuntimeSDK=false"],"command":["/manager"],"env":[{"name":"POD_NAMESPACE","valueFrom":{"fieldRef":{"fieldPath":"metadata.namespace"}}},{"name":"POD_NAME","valueFrom":{"fieldRef":{"fieldPath":"metadata.name"}}},{"name":"POD_UID","valueFrom":{"fieldRef":{"fieldPath":"metadata.uid"}}}],"image":"registry.k8s.io/cluster-api/cluster-api-controller:v1.2.5","imagePullPolicy":"IfNotPresent","livenessProbe":{"httpGet":{"path":"/healthz","port":"healthz"}},"name":"manager","ports":[{"containerPort":9443,"name":"webhook-server","protocol":"TCP"},{"containerPort":9440,"name":"healthz","protocol":"TCP"}],"readinessProbe":{"httpGet":{"path":"/readyz","port":"healthz"}},"resources":{},"volumeMounts":[{"mountPath":"/tmp/k8s-webhook-server/serving-certs","name":"cert","readOnly":true}]}],"serviceAccountName":"capi-manager","terminationGracePeriodSeconds":10,"tolerations":[{"effect":"NoSchedule","key":"node-role.kubernetes.io/master"},{"effect":"NoSchedule","key":"node-role.kubernetes.io/control-plane"}],"volumes":[{"name":"cert","secret":{"secretName":"capi-webhook-service-cert"}}]}}},"status":{}}
I1118 11:02:05.173652       1 round_trippers.go:466] curl -v -XPATCH  -H "Accept: application/json, */*" -H "Content-Type: application/merge-patch+json" -H "User-Agent: clusterctl/ (linux/amd64)" -H "Authorization: Bearer <masked>" 'https://10.96.0.1:443/apis/apps/v1/namespaces/capi-system/deployments/capi-controller-manager?timeout=30s'
I1118 11:02:05.209545       1 round_trippers.go:553] PATCH https://10.96.0.1:443/apis/apps/v1/namespaces/capi-system/deployments/capi-controller-manager?timeout=30s 200 OK in 35 milliseconds
```

**Comment by primeroz** [comment]
FYI i changed the clusterrole in the chart to 

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: capi-visualizer
rules:
# TODO: Consider restricting the rights to the relevant CAPI apiGroups.
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - 'watch'
  - 'list'
  - 'get'
- nonResourceURLs:
  - '*'
  verbs:
  - '*'
```

and the capi-controller-manager is not unchanged.

I could push a similar PR here but i guess it would be good to understand why this is happening ?

**Comment by primeroz** [comment]
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: capi-visualizer
rules:
# TODO: Consider restricting the rights to the relevant CAPI apiGroups.
- apiGroups:
  - ''
  resources:
  - '*'
  verbs:
  - 'list'
  - 'get'
  - 'watch'
- apiGroups:
  - 'cluster.x-k8s.io'
  - 'addons.cluster.x-k8s.io'
  - 'bootstrap.cluster.x-k8s.io'
  - 'controlplane.cluster.x-k8s.io'
  - 'ipam.cluster.x-k8s.io'
  - 'infrastructure.cluster.x-k8s.io'
  - 'runtime.cluster.x-k8s.io'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - '*'
  verbs:
  - '*'
```

this is better

**Comment by Jont828** [comment]
@primeroz Thanks for sharing this bug! I'm not sure why the visualizer would be upgrading the CAPI controller to v1.2.5 since the app imports Cluster API v1.2.0 as a library [on this line](https://github.com/Jont828/cluster-api-visualizer/blob/bdf6ae85c3a8b1ff2b1cad80f4e443f713c5b252/go.mod#L13). Did you find this issue in only CAPZ Tilt for v1.6.0 or do you think this is a cross-version issue?

**Comment by primeroz** [comment]
> Did you find this issue in only CAPZ Tilt for v1.6.0 

I only tested on the latest version since this was the first time for me with capz so i don't know

>  I'm not sure why the visualizer would be upgrading the CAPI controller to v1.2.5
I did try to spend some time trying to understand the `why` but i failed. I could not see anything in code that would trigger such an update 

I also tried to start Tilt with capi 1.2.5 and the replacement of the flags would still happen ! 

So i can only confirm the issue `experimentally` 

* watching the capi-controller and see the deployment get updated when capi-visualizer start up
* disabling the capi-visualizer from the Tiltfile -> No replacement happen
* restrict rbac for capi-visualizer to prevent it from updating deployments -> No replacement happen ( and no rbac errors either )

**Comment by Jont828** [comment]
It seems like your change works for the Helm chart, but I found that the issue is happening even if I run the app locally using go and npm. It seems like another issue is causing this, I'll look into it more.

**Comment by primeroz** [comment]
yes, i did not find or fix the actual root cause. I just updated the RBAC to prevent the upgrade event from happening

**Comment by Jont828** [comment]
I noticed that with the management cluster overview screen seems to take about 30-60 sec to load with the RBAC changes. I'm wondering if it's attempting the upgrade and timing out because it no longer has permission. Let me look into this some more!

**Comment by primeroz** [comment]
It make sense. I was surprised I did not see any forbidden log with the updated rbac

**Comment by Jont828** [comment]
I think I figured it out, it looks like the app was making a call to `clusterctl init` when we set up the clients, which was leading to CAPI being reinstalled.

**Comment by Jont828** [comment]
Yeah, I think so, I left a few comments and I think we should be good to cut a patch release.
