### ISSUE TITLE
Ensure visualizer works offline

### ISSUE THREAD

**Issue by sbueringer** [Jont828/cluster-api-visualizer#16]
We tried to use the visualizer without internet for our KubeCon tutorial and it turns out it loads some css files from the Internet.

(but this works if they are already cached before)

To reproduce:
* Start the visualizer image
* Disconnect
* Try to reload the page with cache refresh

<img width="1962" alt="image" src="https://user-images.githubusercontent.com/4662360/204211119-f0fda329-6cab-4209-8d5d-5b601e71e122.png">

Would be nice if those files could be builtin so the visualizer doesn't need internet access.

**Comment by sbueringer** [comment]
cc @killianmuldoon

**Comment by Jont828** [comment]
@sbueringer Should be fixed as a part of #17, let me know if this works on your end!

**Comment by sbueringer** [comment]
Works, thx!
