### ISSUE TITLE
Show non-Cluster API resources that exist in the ownership hierarchy of a Cluster

### ISSUE THREAD

**Issue by nojnhuh** [Jont828/cluster-api-visualizer#42]
Since CAPZ now uses Azure Service Operator to drive most of its reconciliation, it would be awesome if the visualizer could also show those ASO resources in the resource graph.

**Comment by Jont828** [comment]
That sounds super cool, I think we'd just need a generalized way to figure out how to query for resources and their associated types.

**Comment by Jont828** [comment]
Should be done with #43!

**Comment by illrill** [comment]
Thanks @Jont828!

@nojnhuh, looks like we need to add the label `visualizer.cluster.x-k8s.io: ""` to all ASO CRDs and the label `cluster.x-k8s.io/cluster-name: <cluster-name>` to all ASO CRs, in order to push this across the finish line.

**Comment by Jont828** [comment]
@illrill I got a branch with some changes I used to test this, can open a PR in CAPZ soon.
