### ISSUE TITLE
Feature Request: Group all Addons under a single node.

### ISSUE THREAD

**Issue by sl1pm4t** [Jont828/cluster-api-visualizer#79]
Currently all addons (ClusterResourceSets and Helm Addons) are direct descendants of the `Cluster` object.
On our clusters, we deploy 4-5 addons, and so this causes the cluster resource tree to spread horizontally, with the addons taking up a lot of visual space.

It would be nice if all the addons could be represented under an "Addons" node, so all the children could be collapsed in a single click if required.

This is possibly similar to how the node MachineSets/Deployments/Pools are all attached under the `Workers` virtual node.

**Comment by Jont828** [comment]
Makes sense to me, I can get started on that.
